name = "naughty-company-api"
main = "src/worker/index.ts"
compatibility_date = "2026-10-08"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "naughty-company-dashboard"
database_id = "bbbe128a-c5cc-46ec-b8ef-93860183e795"
migrations_dir = "migrations/auth"
