import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import type { CompanyDashboardModel } from "../../lib/company/types"
import { LineChart } from "./chart-utils"
import type { ChartSeries } from "./chart-utils"

type View = "executive" | "health" | "trends" | "member-insights" | "roster-insights" | "layout"
type HealthCompany = { companyId: string; companyName: string; companyType?: string | null; fetchedAt: string; snapshotCount: number; ageHours: number | null; freshness: "fresh" | "aging" | "stale" | "unknown" | "never" }
type Health = { checkedAt: string; worker: { status: string; latencyMs?: number }; database: { status: string; latencyMs?: number }; summary: { companyCount: number; snapshotCount: number; latestSnapshotAt: string | null; staleCompanies: number }; companies: HealthCompany[] }
type TrendPoint = { day: string; fetchedAt: string; dailyIncome: number | null; weeklyIncome: number | null; rating: number | null; employeeCount: number; employeeCapacity: number | null }
type Trends = { company: { companyId: string; companyName: string; companyType?: string }; range: string; history: TrendPoint[]; summary: { snapshotCount: number; firstSnapshotAt?: string | null; latestSnapshotAt?: string | null; dailyIncomeChange: number | null; dailyIncomeChangePercent: number | null; weeklyIncomeChange: number | null; ratingChange: number | null; employeeCountChange: number | null } }
type RosterEmployee = { id: string; name: string; position: string; daysInCompany: number | null; manualLabor: number | null; intelligence: number | null; endurance: number | null; wage: number | null; effectiveness: number | null; status: string | null; lastAction: string | null }
type Roster = { company: { companyId: string; companyName: string; companyType: string; fetchedAt: string; employeesHired: number | null; employeeCapacity: number | null } | null; roster: RosterEmployee[]; summary: { rosterCount: number; employeeCapacity: number | null; averageManualLabor: number | null; averageIntelligence: number | null; averageEndurance: number | null; averageEffectiveness: number | null; knownStatsCount: number; knownWageCount: number; totalKnownWages: number; positions: Array<{ position: string; count: number }>; snapshotCount: number; firstSnapshotAt: string | null; latestSnapshotAt: string | null } | null; message?: string }
type MemberActivity = { rangeDays: number; summary: { totalMembers: number; activeMembers: number; newMembers: number; withoutCompany: number }; members: Array<{ playerId: string; playerName: string; createdAt: string; lastActiveAt: string; snapshotCount: number; latestCompanyAt: string | null }> }
type Widget = { id: string; visible: boolean; order: number }
type DashboardPreferences = { density: "comfortable" | "compact"; contentWidth: "standard" | "wide" }
type Layout = { widgets: Widget[]; dashboardPreferences?: DashboardPreferences }
type Props = { view: View; apiBase: string; sessionToken: string; isAdmin: boolean; demoMode: boolean; companyId: string; model: CompanyDashboardModel | null; companyRank: string; starRank: string; nextStarGap: number | null; sameTypeCount: number; dashboardPreferences: DashboardPreferences; onDashboardPreferencesChange: (preferences: DashboardPreferences) => void; onNavigate: (view: View) => void }

const DEFAULT_WIDGETS: Widget[] = [
  { id: "company-health", visible: true, order: 0 }, { id: "income-performance", visible: true, order: 1 },
  { id: "roster-overview", visible: true, order: 2 }, { id: "recent-trends", visible: true, order: 3 },
  { id: "automation-status", visible: true, order: 4 }, { id: "alerts", visible: true, order: 5 }, { id: "rankings", visible: true, order: 6 },
]
const WIDGET_META: Record<string, { title: string; description: string }> = {
  "company-health": { title: "Company & data health", description: "Connection freshness and saved history coverage" },
  "income-performance": { title: "Income performance", description: "Current income and change across the selected history window" },
  "roster-overview": { title: "Roster overview", description: "Staffing, capacity, skill coverage, and wage totals" },
  "recent-trends": { title: "Recent trends", description: "Latest daily income readings" },
  "automation-status": { title: "Automation status", description: "Latest scheduled run and alert activity" },
  alerts: { title: "Alert inbox", description: "Recent private automation alerts" },
  rankings: { title: "Competitive position", description: "Current company rating and staffing indicators" },
}

async function api<T>(base: string, token: string, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${base}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, ...(init.body !== undefined ? { "content-type": "application/json" } : {}), ...(init.headers || {}) } })
  const payload = await response.json().catch(() => ({})) as { error?: string } & Record<string, unknown>
  if (!response.ok) throw new Error(payload.error || `Request failed (${response.status}).`)
  return payload as T
}
function money(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "—" : "$" + value.toLocaleString(undefined, { maximumFractionDigits: 0 }) }
function number(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: 1 }) }
function date(value?: string | null) { if (!value) return "Not recorded"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) }
function ageLabel(hours: number | null) { if (hours == null) return "No snapshot"; if (hours < 1) return `${Math.round(hours * 60)}m ago`; if (hours < 48) return `${number(hours)}h ago`; return `${number(hours / 24)}d ago` }
function average(values: Array<number | null>, predicate: (value: number) => boolean = () => true) { const valid = values.filter((value): value is number => typeof value === "number" && Number.isFinite(value) && predicate(value)); return valid.length ? valid.reduce((sum, value) => sum + value, 0) / valid.length : null }
function percent(current: number | null, previous: number | null) { return current == null || previous == null || previous === 0 ? null : (current - previous) / Math.abs(previous) * 100 }
function changeLabel(value: number | null, suffix = "%") { if (value == null || !Number.isFinite(value)) return "Not enough history"; return `${value > 0 ? "+" : ""}${number(value)}${suffix}` }

export function InsightsWorkspace({ view, apiBase, sessionToken, isAdmin, demoMode, companyId, model, companyRank, starRank, nextStarGap, sameTypeCount, dashboardPreferences, onDashboardPreferencesChange, onNavigate }: Props) {
  const [health, setHealth] = useState<Health | null>(null)
  const [trends, setTrends] = useState<Trends | null>(null)
  const [trendDays, setTrendDays] = useState<"7" | "30" | "90" | "365" | "all">("90")
  const [comparisonDays, setComparisonDays] = useState<"7" | "30" | "90">("7")
  const [roster, setRoster] = useState<Roster | null>(null)
  const [memberActivity, setMemberActivity] = useState<MemberActivity | null>(null)
  const [memberActivityDays, setMemberActivityDays] = useState<"7" | "30" | "90" | "365">("30")
  const [memberSearch, setMemberSearch] = useState("")
  const [alerts, setAlerts] = useState<Array<{ eventId: string; title: string; message: string; severity: string; status: string; createdAt: string }>>([])
  const [automation, setAutomation] = useState<{ runs: Array<{ status: string; startedAt: string; finishedAt?: string | null; companiesFailed: number; alertsCreated: number }>; insights?: { successRate: number | null; totalRuns: number } } | null>(null)
  const [widgets, setWidgets] = useState<Widget[]>(DEFAULT_WIDGETS)
  const [loading, setLoading] = useState(false)
  const [savingLayout, setSavingLayout] = useState(false)
  const [error, setError] = useState("")
  const [notice, setNotice] = useState("")
  const [layoutLoaded, setLayoutLoaded] = useState(false)
  const trendRequestId = useRef(0)
  const rosterRequestId = useRef(0)
  const healthRequestId = useRef(0)
  const layoutRequestId = useRef(0)

  const loadHealth = useCallback(async () => { const requestId = ++healthRequestId.current; if (!sessionToken || demoMode) return; const payload = await api<Health>(apiBase, sessionToken, "/api/me/health"); if (requestId === healthRequestId.current) setHealth(payload) }, [apiBase, sessionToken, demoMode])
  const loadTrends = useCallback(async () => { const requestId = ++trendRequestId.current; if (!sessionToken || demoMode || !companyId) { setTrends(null); return }; setTrends(null); const payload = await api<Trends>(apiBase, sessionToken, `/api/me/companies/${encodeURIComponent(companyId)}/history?days=${trendDays}`); if (requestId === trendRequestId.current) setTrends(payload) }, [apiBase, sessionToken, demoMode, companyId, trendDays])
  const loadRoster = useCallback(async () => { const requestId = ++rosterRequestId.current; if (!sessionToken || demoMode) { setRoster(null); return }; setRoster(null); const payload = await api<Roster>(apiBase, sessionToken, `/api/me/member-insights${companyId ? `?companyId=${encodeURIComponent(companyId)}` : ""}`); if (requestId === rosterRequestId.current) setRoster(payload) }, [apiBase, sessionToken, demoMode, companyId])
  const loadLayout = useCallback(async () => { const requestId = ++layoutRequestId.current; if (!sessionToken || demoMode) { setLayoutLoaded(true); return }; setLayoutLoaded(false); try { const localPreferences = (() => { try { return JSON.parse(localStorage.getItem("ncd_dashboard_preferences") || "null") as DashboardPreferences | null } catch { return null } })(); if (localPreferences && requestId === layoutRequestId.current) onDashboardPreferencesChange({ density: localPreferences.density === "compact" ? "compact" : "comfortable", contentWidth: localPreferences.contentWidth === "wide" ? "wide" : "standard" }); const payload = await api<{ layout: Layout | null }>(apiBase, sessionToken, "/api/me/dashboard-layout"); const saved = payload.layout?.widgets; if (requestId === layoutRequestId.current && payload.layout?.dashboardPreferences) { const preferences = { density: payload.layout.dashboardPreferences.density === "compact" ? "compact" as const : "comfortable" as const, contentWidth: payload.layout.dashboardPreferences.contentWidth === "wide" ? "wide" as const : "standard" as const }; onDashboardPreferencesChange(preferences); try { localStorage.setItem("ncd_dashboard_preferences", JSON.stringify(preferences)) } catch { /* Storage may be disabled. */ } } if (requestId === layoutRequestId.current && Array.isArray(saved) && saved.length) { const map = new Map(saved.map((item) => [item.id, item])); setWidgets(DEFAULT_WIDGETS.map((item) => map.get(item.id) ?? item).sort((a, b) => a.order - b.order).map((item, order) => ({ ...item, order }))) } } catch { /* Keep a usable default layout when a legacy Worker has not deployed this route yet. */ } finally { if (requestId === layoutRequestId.current) setLayoutLoaded(true) } }, [apiBase, sessionToken, demoMode, onDashboardPreferencesChange])

  useEffect(() => {
    if (demoMode || !sessionToken) { setLoading(false); return }
    let cancelled = false
    async function load() {
      setLoading(true); setError("")
      const tasks: Promise<unknown>[] = []
      if (view === "health" || view === "executive") tasks.push(loadHealth())
      if (view === "trends" || view === "executive") tasks.push(loadTrends())
      if (view === "roster-insights" || view === "executive") tasks.push(loadRoster())
      if (view === "executive") tasks.push(api<{ events: typeof alerts }>(apiBase, sessionToken, "/api/me/alerts?limit=5").then((p) => { if (!cancelled) setAlerts(p.events || []) }))
      if (view === "executive" && isAdmin) tasks.push(api<typeof automation>(apiBase, sessionToken, "/api/admin/automation/runs?limit=1&days=30").then((p) => { if (!cancelled) setAutomation(p) }))
      if (view === "member-insights" && isAdmin) { setMemberActivity(null); tasks.push(api<MemberActivity>(apiBase, sessionToken, `/api/admin/member-activity?days=${memberActivityDays}`).then((p) => { if (!cancelled) setMemberActivity(p) })) }
      if (view === "executive" || view === "layout") tasks.push(loadLayout())
      const results = await Promise.allSettled(tasks)
      if (!cancelled) { const failed = results.find((result) => result.status === "rejected") as PromiseRejectedResult | undefined; if (failed) setError(failed.reason instanceof Error ? failed.reason.message : "Some insights could not be loaded."); setLoading(false) }
    }
    void load()
    return () => { cancelled = true; trendRequestId.current += 1; rosterRequestId.current += 1; healthRequestId.current += 1; layoutRequestId.current += 1 }
  }, [view, apiBase, sessionToken, demoMode, isAdmin, companyId, trendDays, memberActivityDays, loadHealth, loadTrends, loadRoster, loadLayout])

  const dailySeries: ChartSeries[] = useMemo(() => [{ label: trends?.company.companyName || model?.company.name || "Selected company", values: (trends?.history || []).map((point) => ({ label: point.day, value: point.dailyIncome })) }], [trends, model])
  const weeklySeries: ChartSeries[] = useMemo(() => [{ label: trends?.company.companyName || model?.company.name || "Selected company", values: (trends?.history || []).map((point) => ({ label: point.day, value: point.weeklyIncome })) }], [trends, model])
  const ratingSeries: ChartSeries[] = useMemo(() => [{ label: "Star rating", values: (trends?.history || []).map((point) => ({ label: point.day, value: point.rating })) }], [trends])
  const rosterSeries: ChartSeries[] = useMemo(() => [{ label: "Employees", values: (trends?.history || []).map((point) => ({ label: point.day, value: point.employeeCount })) }], [trends])
  const comparison = useMemo(() => { const points = trends?.history || []; if (points.length < 2) return null; const periodMs = Number(comparisonDays) * 86400000; const latestDay = Date.parse(`${points[points.length - 1].day}T00:00:00Z`); const recent = points.filter((point) => { const delta = latestDay - Date.parse(`${point.day}T00:00:00Z`); return delta >= 0 && delta < periodMs }); const previous = points.filter((point) => { const delta = latestDay - Date.parse(`${point.day}T00:00:00Z`); return delta >= periodMs && delta < periodMs * 2 }); return { recentAverage: average(recent.map((point) => point.dailyIncome)), previousAverage: average(previous.map((point) => point.dailyIncome)), recentCount: recent.length, previousCount: previous.length } }, [trends, comparisonDays])
  const visibleWidgets = [...widgets].sort((a, b) => a.order - b.order).filter((widget) => widget.visible)

  async function saveLayout(next = widgets) {
    if (!sessionToken || demoMode) { setError("Sign in to save a personal dashboard layout."); return }
    setSavingLayout(true); setError(""); setNotice("")
    try { const normalized = next.map((item, order) => ({ ...item, order })); await api(apiBase, sessionToken, "/api/me/dashboard-layout", { method: "POST", body: JSON.stringify({ widgets: normalized, dashboardPreferences }) }); try { localStorage.setItem("ncd_dashboard_preferences", JSON.stringify(dashboardPreferences)) } catch { /* Storage may be disabled. */ } setWidgets(normalized); setNotice("Executive Overview layout saved. Dashboard appearance saved on this browser.") }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save the dashboard layout.") }
    finally { setSavingLayout(false) }
  }
  function toggleWidget(id: string) { if (!layoutLoaded || savingLayout) return; setWidgets((current) => current.map((item) => item.id === id ? { ...item, visible: !item.visible } : item)) }
  function moveWidget(id: string, direction: -1 | 1) { if (!layoutLoaded || savingLayout) return; setWidgets((current) => { const sorted = [...current].sort((a, b) => a.order - b.order); const index = sorted.findIndex((item) => item.id === id), target = index + direction; if (target < 0 || target >= sorted.length) return current; [sorted[index], sorted[target]] = [sorted[target], sorted[index]]; return sorted.map((item, order) => ({ ...item, order })) }) }

  if (demoMode || !sessionToken) return <div className="insights-workspace"><section className="panel insights-intro"><span className="automation-eyebrow">COMPANY INTELLIGENCE</span><h2>{viewTitle(view)}</h2><p>Sign in to load private company history, roster metrics, API health, and saved dashboard preferences. Demo data is not written to your account.</p></section><div className="empty-state">Live insights require an authenticated dashboard session.</div></div>

  const freshnessClass = (value: string) => value === "fresh" ? "good" : value === "stale" ? "danger" : value === "aging" ? "warning" : "neutral"
  const renderWidget = (id: string) => {
    if (id === "company-health") return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("health")}>Details ↗</button></div><div className="executive-stat-row"><div><small>WORKER</small><strong className={health?.worker.status === "ok" ? "metric-good" : "metric-warning"}>{health?.worker.status || "—"}</strong></div><div><small>DATABASE</small><strong className={health?.database.status === "ok" ? "metric-good" : "metric-warning"}>{health?.database.status || "—"}</strong></div><div><small>SNAPSHOTS</small><strong>{number(health?.summary.snapshotCount)}</strong></div><div><small>STALE COMPANIES</small><strong>{number(health?.summary.staleCompanies)}</strong></div></div></article>
    if (id === "income-performance") return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("trends")}>Trends ↗</button></div><div className="executive-stat-row"><div><small>DAILY INCOME</small><strong>{money(model?.company.dailyIncome)}</strong></div><div><small>WEEKLY INCOME</small><strong>{money(model?.company.weeklyIncome)}</strong></div><div><small>WINDOW CHANGE</small><strong>{changeLabel(trends?.summary.dailyIncomeChangePercent ?? null)}</strong></div><div><small>STAR RATING</small><strong>{model?.company.rating == null ? "—" : `${model.company.rating} ★`}</strong></div></div>{comparison && <p className="field-hint">Recent daily average: {money(comparison.recentAverage)} vs prior 7-day average {money(comparison.previousAverage)} ({changeLabel(percent(comparison.recentAverage, comparison.previousAverage))}).</p>}</article>
    if (id === "roster-overview") return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("member-insights")}>Roster ↗</button></div><div className="executive-stat-row"><div><small>EMPLOYEES</small><strong>{number(roster?.summary?.rosterCount ?? model?.employees.length)}</strong></div><div><small>CAPACITY</small><strong>{number(roster?.summary?.employeeCapacity ?? model?.company.employeeCapacity)}</strong></div><div><small>AVG EFFECTIVENESS</small><strong>{number(roster?.summary?.averageEffectiveness)}%</strong></div><div><small>KNOWN WAGES</small><strong>{money(roster?.summary?.totalKnownWages)}</strong></div></div></article>
    if (id === "recent-trends") return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("trends")}>Open history ↗</button></div>{trends?.history.length ? <LineChart title="Daily income" money series={dailySeries} /> : <div className="empty-state">No saved history is available for the selected company yet.</div>}</article>
    if (id === "automation-status") return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("health")}>Health ↗</button></div><div className="executive-stat-row"><div><small>LATEST RUN</small><strong>{automation?.runs?.[0]?.status || "Not loaded"}</strong></div><div><small>SUCCESS RATE</small><strong>{automation?.insights?.successRate == null ? "—" : `${automation.insights.successRate}%`}</strong></div><div><small>RECENT ALERTS</small><strong>{alerts.length}</strong></div><div><small>UNREAD</small><strong>{alerts.filter((item) => item.status === "unread").length}</strong></div></div></article>
    if (id === "alerts") return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("health")}>Status ↗</button></div>{alerts.length ? <div className="executive-alert-list">{alerts.slice(0, 4).map((item) => <div key={item.eventId}><span className={`automation-event-severity ${item.severity}`}>●</span><div><strong>{item.title}</strong><small>{item.message}</small><small>{date(item.createdAt)} · {item.status}</small></div></div>)}</div> : <div className="empty-state">No automation alerts are recorded.</div>}</article>
    return <article className="panel executive-widget" key={id}><div className="panel-heading"><div><h3>{WIDGET_META[id].title}</h3><p>{WIDGET_META[id].description}</p></div><button type="button" className="text-button" onClick={() => onNavigate("trends")}>History ↗</button></div><div className="executive-stat-row"><div><small>COMPANY RANK</small><strong>{companyRank}</strong><span>{sameTypeCount.toLocaleString()} same-type companies</span></div><div><small>STAR RANK</small><strong>{starRank}</strong><span>{model?.company.rating == null ? "Rating unavailable" : `${model.company.rating} ★ current rating`}</span></div><div><small>GAP TO NEXT STAR</small><strong>{money(nextStarGap)}</strong><span>Weekly income benchmark gap</span></div><div><small>ROSTER FIT</small><strong>{model ? `${model.employeesMeetingRequirements}/${model.employees.length}` : "—"}</strong><span>Employees meeting mapped requirements</span></div></div></article>
  }

  return <div className="insights-workspace">
    <section className="panel insights-intro"><div><span className="automation-eyebrow">COMPANY INTELLIGENCE / {view.toUpperCase().replaceAll("-", " ")}</span><h2>{viewTitle(view)}</h2><p>{viewDescription(view)}</p></div><div className="insights-intro-actions"><span className="count-chip">{model?.company.name || "No company selected"}</span>{(view === "executive" || view === "layout") && <button type="button" className="secondary-button" onClick={() => onNavigate(view === "executive" ? "layout" : "executive")}>{view === "executive" ? "Customize layout" : "Preview overview"} ↗</button>}</div></section>
    {error && <div className="error-banner" role="alert">{error}</div>}{notice && <div className="automation-notice" role="status">{notice}</div>}
    {loading && <div className="insights-loading">Refreshing your intelligence workspace…</div>}
    {view === "executive" && <><div className="executive-toolbar"><span>{visibleWidgets.length} of {widgets.length} widgets visible</span><button type="button" className="text-button" onClick={() => onNavigate("layout")}>Manage dashboard widgets →</button></div>{!layoutLoaded ? <div className="empty-state">Loading your saved dashboard layout…</div> : visibleWidgets.length ? <div className="executive-grid">{visibleWidgets.map((widget) => renderWidget(widget.id))}</div> : <div className="empty-state">Your overview has no visible widgets. Customize the layout to add panels.</div>}</>}
    {view === "health" && <>
      <div className="admin-metric-grid insights-metrics"><article className="admin-metric-card"><small>Worker API</small><strong className={health?.worker.status === "ok" ? "metric-good" : "metric-warning"}>{health?.worker.status || "Unknown"}</strong><span className="admin-insight-footnote">{health?.worker.latencyMs == null ? "Waiting for probe" : `${number(health.worker.latencyMs)} ms response time`} · checked {date(health?.checkedAt)}</span></article><article className="admin-metric-card"><small>D1 database</small><strong className={health?.database.status === "ok" ? "metric-good" : "metric-warning"}>{health?.database.status || "Unknown"}</strong><span className="admin-insight-footnote">{health?.database.latencyMs == null ? "Waiting for probe" : `${number(health.database.latencyMs)} ms query time`} · authenticated storage probe</span></article><article className="admin-metric-card"><small>Company snapshots</small><strong>{number(health?.summary.snapshotCount)}</strong><span className="admin-insight-footnote">Saved for your account</span></article><article className="admin-metric-card"><small>Stale connections</small><strong>{number(health?.summary.staleCompanies)}</strong><span className="admin-insight-footnote">No successful snapshot in 24+ hours</span></article></div>
      <section className="panel insights-table-panel"><div className="panel-heading"><div><h3>Company data freshness</h3><p>Fresh under 12 hours · aging 12 to 24 hours · stale 24 hours or older.</p></div><button type="button" className="secondary-button" onClick={() => { setLoading(true); void loadHealth().catch((caught) => setError(caught instanceof Error ? caught.message : "Health check failed.")).finally(() => setLoading(false)) }}>Run health check ↻</button></div>{health?.companies.length ? <div className="table-scroll"><table className="admin-table"><thead><tr><th>COMPANY</th><th>TYPE</th><th>LAST SUCCESSFUL SNAPSHOT</th><th>AGE</th><th>HISTORY</th><th>STATUS</th></tr></thead><tbody>{health.companies.map((item) => <tr key={item.companyId}><td><strong>{item.companyName || `Company #${item.companyId}`}</strong><small>#{item.companyId}</small></td><td>{item.companyType || "Unknown"}</td><td>{date(item.fetchedAt)}</td><td>{ageLabel(item.ageHours)}</td><td>{number(item.snapshotCount)}</td><td><span className={`admin-status ${freshnessClass(item.freshness)}`}>{item.freshness === "never" ? "never synced" : item.freshness}</span></td></tr>)}</tbody></table></div> : <div className="empty-state">No company snapshots are available yet. Connect a company and complete a successful refresh.</div>}</section>
      <section className="panel insights-note"><h3>What this health check covers</h3><p>The Worker and D1 are probed separately. Company freshness reflects the last saved successful snapshot, not a claim that Torn's API is currently reachable. A stale snapshot is a signal to refresh or inspect the saved connection, not evidence of an outage.</p></section>
    </>}
    {view === "trends" && <>
      <div className="insights-range-toolbar"><label>History window<select value={trendDays} onChange={(event) => setTrendDays(event.target.value as typeof trendDays)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">12 months</option><option value="all">All available history</option></select></label><span>{number(trends?.summary.snapshotCount)} daily reporting points · latest {date(trends?.summary.latestSnapshotAt)}</span></div>
      <div className="admin-metric-grid insights-metrics"><article className="admin-metric-card"><small>Daily income change</small><strong>{money(trends?.summary.dailyIncomeChange)}</strong><span className="admin-insight-footnote">{changeLabel(trends?.summary.dailyIncomeChangePercent ?? null)}</span></article><article className="admin-metric-card"><small>Weekly income change</small><strong>{money(trends?.summary.weeklyIncomeChange)}</strong><span className="admin-insight-footnote">First vs latest point in range</span></article><article className="admin-metric-card"><small>Star-rating change</small><strong>{changeLabel(trends?.summary.ratingChange ?? null, " ★")}</strong><span className="admin-insight-footnote">Historical profile snapshots</span></article><article className="admin-metric-card"><small>Roster change</small><strong>{changeLabel(trends?.summary.employeeCountChange ?? null, " employees")}</strong><span className="admin-insight-footnote">Employee headcount over range</span></article></div>
      <section className="panel period-comparison"><div className="panel-heading"><div><h3>Period-over-period comparison</h3><p>Compare equal-length windows using recorded snapshots. The recent window ends on the latest saved reporting date.</p></div><label>Comparison window<select value={comparisonDays} onChange={(event) => setComparisonDays(event.target.value as typeof comparisonDays)}><option value="7">7 vs prior 7 days</option><option value="30">30 vs prior 30 days</option><option value="90">90 vs prior 90 days</option></select></label></div><div className="period-comparison-grid"><div><small>RECENT {comparisonDays}-DAY AVERAGE</small><strong>{money(comparison?.recentAverage)}</strong><span>{comparison?.recentCount ?? 0} reporting days</span></div><div><small>PREVIOUS {comparisonDays}-DAY AVERAGE</small><strong>{money(comparison?.previousAverage)}</strong><span>{comparison?.previousCount ?? 0} reporting days</span></div><div><small>CHANGE</small><strong>{changeLabel(percent(comparison?.recentAverage ?? null, comparison?.previousAverage ?? null))}</strong><span>{comparison?.previousCount ? "Based on available daily snapshots" : "Not enough prior-period history"}</span></div></div></section>
      <div className="insights-chart-grid"><LineChart title="Daily income" money series={dailySeries}/><LineChart title="Weekly income" money series={weeklySeries}/><LineChart title="Star-rating history" series={ratingSeries}/><LineChart title="Employee roster size" series={rosterSeries}/></div>
      <section className="panel insights-table-panel"><div className="panel-heading"><div><h3>Historical reporting points</h3><p>One point per reporting date, using the latest successful snapshot recorded on that date.</p></div></div>{trends?.history.length ? <div className="table-scroll"><table className="admin-table"><thead><tr><th>DATE</th><th>DAILY INCOME</th><th>WEEKLY INCOME</th><th>RATING</th><th>EMPLOYEES</th></tr></thead><tbody>{[...trends.history].reverse().slice(0,100).map((point) => <tr key={point.day}><td>{point.day}</td><td>{money(point.dailyIncome)}</td><td>{money(point.weeklyIncome)}</td><td>{point.rating == null ? "—" : `${number(point.rating)} ★`}</td><td>{number(point.employeeCount)}{point.employeeCapacity == null ? "" : ` / ${point.employeeCapacity}`}</td></tr>)}</tbody></table></div> : <div className="empty-state">No snapshots exist in this window. Choose a longer range or refresh the company to start building history.</div>}</section>
    </>}
    {view === "member-insights" && <>
      {isAdmin ? (memberActivity ? <>
      {memberActivity && isAdmin && <><div className="admin-metric-grid insights-metrics"><article className="admin-metric-card"><small>Dashboard members</small><strong>{number(memberActivity.summary.totalMembers)}</strong></article><article className="admin-metric-card"><small>Active in {memberActivityDays} days</small><strong>{number(memberActivity.summary.activeMembers)}</strong></article><article className="admin-metric-card"><small>New in {memberActivityDays} days</small><strong>{number(memberActivity.summary.newMembers)}</strong></article><article className="admin-metric-card"><small>No connected company</small><strong>{number(memberActivity.summary.withoutCompany)}</strong></article></div><section className="panel insights-table-panel"><div className="panel-heading"><div><h3>Dashboard member activity</h3><p>Recent account updates and saved data coverage. Last activity is based on the account record's last update.</p></div><label>Activity window<select value={memberActivityDays} onChange={(event) => setMemberActivityDays(event.target.value as typeof memberActivityDays)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">12 months</option></select></label></div><label className="automation-alert-search"><span>Search members</span><input type="search" value={memberSearch} onChange={(event) => setMemberSearch(event.target.value)} placeholder="Search member name or ID…" aria-label="Search dashboard member name or ID" /></label><div className="table-scroll"><table className="admin-table"><thead><tr><th>MEMBER</th><th>LAST ACTIVITY</th><th>COMPANY DATA</th><th>SNAPSHOTS</th></tr></thead><tbody>{memberActivity.members.filter((member) => `${member.playerName} ${member.playerId}`.toLowerCase().includes(memberSearch.trim().toLowerCase())).map((member) => <tr key={member.playerId}><td><strong>{member.playerName}</strong><small>#{member.playerId}</small></td><td>{date(member.lastActiveAt)}</td><td>{date(member.latestCompanyAt)}</td><td>{number(member.snapshotCount)}</td></tr>)}</tbody></table></div>{!memberActivity.members.some((member) => `${member.playerName} ${member.playerId}`.toLowerCase().includes(memberSearch.trim().toLowerCase())) && <div className="empty-state">No dashboard members match that search.</div>}</section></>}
      </> : <div className="empty-state">Loading dashboard member activity…</div>) : <div className="empty-state">Member activity insights require administrator access. The dashboard member directory remains available above.</div>}
    </>}
    {view === "roster-insights" && <>
      <div className="admin-metric-grid insights-metrics"><article className="admin-metric-card"><small>Current roster</small><strong>{number(roster?.summary?.rosterCount ?? model?.employees.length)}</strong><span className="admin-insight-footnote">{roster?.company?.companyName || model?.company.name || "No company connected"}</span></article><article className="admin-metric-card"><small>Capacity used</small><strong>{roster?.summary?.employeeCapacity ? `${number((roster.summary.rosterCount / roster.summary.employeeCapacity) * 100)}%` : "—"}</strong><span className="admin-insight-footnote">{number(roster?.summary?.employeeCapacity)} available slots total</span></article><article className="admin-metric-card"><small>Average effectiveness</small><strong>{roster?.summary?.averageEffectiveness == null ? "—" : number(roster.summary.averageEffectiveness)}</strong><span className="admin-insight-footnote">Known employee effectiveness only</span></article><article className="admin-metric-card"><small>Known wages</small><strong>{money(roster?.summary?.totalKnownWages)}</strong><span className="admin-insight-footnote">{number(roster?.summary?.knownWageCount)} employees with wage data</span></article></div>
      {roster?.summary && <section className="panel roster-insights-panel"><div className="panel-heading"><div><h3>Roster capability profile</h3><p>Skill averages exclude restricted or unavailable stats instead of treating them as zero.</p></div><span className="count-chip">{roster.summary.knownStatsCount} / {roster.summary.rosterCount} with full stats</span></div><div className="executive-stat-row"><div><small>AVG MANUAL LABOR</small><strong>{number(roster.summary.averageManualLabor)}</strong></div><div><small>AVG INTELLIGENCE</small><strong>{number(roster.summary.averageIntelligence)}</strong></div><div><small>AVG ENDURANCE</small><strong>{number(roster.summary.averageEndurance)}</strong></div><div><small>HISTORY DEPTH</small><strong>{number(roster.summary.snapshotCount)}</strong></div></div><div className="roster-position-grid">{roster.summary.positions.map((item) => <div key={item.position}><span>{item.position}</span><strong>{item.count}</strong><div><i style={{ width: `${roster.summary!.rosterCount ? item.count / roster.summary!.rosterCount * 100 : 0}%` }} /></div></div>)}</div></section>}
      <section className="panel insights-table-panel"><div className="panel-heading"><div><h3>Employee roster</h3><p>Role mix, work stats, effectiveness, wage, tenure, and last-action context from your latest successful snapshot.</p></div><span className="count-chip">{roster?.roster.length ?? 0} employees</span></div>{roster?.roster.length ? <div className="table-scroll"><table className="admin-table roster-table"><thead><tr><th>EMPLOYEE</th><th>POSITION</th><th>MAN / INT / END</th><th>EFFECTIVENESS</th><th>WAGE</th><th>TENURE</th><th>LAST ACTION</th></tr></thead><tbody>{roster.roster.map((employee) => <tr key={employee.id || employee.name}><td><strong>{employee.name}</strong><small>{employee.status || "Status unavailable"}</small></td><td>{employee.position}</td><td>{[employee.manualLabor, employee.intelligence, employee.endurance].map((value) => value == null ? "—" : number(value)).join(" / ")}</td><td>{employee.effectiveness == null ? "—" : number(employee.effectiveness)}</td><td>{money(employee.wage)}</td><td>{employee.daysInCompany == null ? "—" : `${number(employee.daysInCompany)} days`}</td><td>{employee.lastAction || "—"}</td></tr>)}</tbody></table></div> : <div className="empty-state">No employee roster is available. Connect a company with employee access and refresh its snapshot.</div>}</section>
    </>}
    {view === "layout" && <>
      <section className="panel dashboard-layout-editor"><div className="panel-heading"><div><h3>Dashboard-wide appearance</h3><p>These preferences apply immediately across Company, Rankings, References, and Settings. Changes preview immediately. Appearance is saved in this browser; Executive Overview widget order is saved to your dashboard account.</p></div><span className="count-chip">Global</span></div>
        <div className="dashboard-preference-grid">
          <label className="dashboard-preference-card"><span><strong>Content density</strong><small>Choose how much information fits on each page.</small></span><select value={dashboardPreferences.density} disabled={!layoutLoaded || savingLayout} onChange={(event) => onDashboardPreferencesChange({ ...dashboardPreferences, density: event.target.value as DashboardPreferences["density"] })}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label>
          <label className="dashboard-preference-card"><span><strong>Content width</strong><small>Use a standard reading width or spread content across wide screens.</small></span><select value={dashboardPreferences.contentWidth} disabled={!layoutLoaded || savingLayout} onChange={(event) => onDashboardPreferencesChange({ ...dashboardPreferences, contentWidth: event.target.value as DashboardPreferences["contentWidth"] })}><option value="standard">Standard</option><option value="wide">Wide</option></select></label>
        </div>
      </section>
      <section className="panel dashboard-layout-editor"><div className="panel-heading"><div><h3>Executive Overview widgets</h3><p>These controls affect only the Executive Overview. Show or hide its panels and arrange their order.</p></div><span className="count-chip">{widgets.filter((item) => item.visible).length} visible</span></div>{!layoutLoaded && <div className="empty-state">Loading saved layout…</div>}<div className="dashboard-widget-list">{[...widgets].sort((a, b) => a.order - b.order).map((widget, index, all) => <article className={`dashboard-widget-option ${widget.visible ? "visible" : "hidden"}`} key={widget.id}><span className="dashboard-widget-grip">{String(index + 1).padStart(2,"0")}</span><div className="dashboard-widget-copy"><strong>{WIDGET_META[widget.id]?.title || widget.id}</strong><small>{WIDGET_META[widget.id]?.description || "Dashboard panel"}</small></div><label className="dashboard-widget-toggle"><input type="checkbox" checked={widget.visible} disabled={!layoutLoaded || savingLayout} onChange={() => toggleWidget(widget.id)} /><span>{widget.visible ? "Visible" : "Hidden"}</span></label><div className="dashboard-widget-order"><button type="button" className="secondary-button" aria-label={`Move ${WIDGET_META[widget.id]?.title} up`} disabled={!layoutLoaded || savingLayout || index === 0} onClick={() => moveWidget(widget.id,-1)}>↑</button><button type="button" className="secondary-button" aria-label={`Move ${WIDGET_META[widget.id]?.title} down`} disabled={!layoutLoaded || savingLayout || index === all.length - 1} onClick={() => moveWidget(widget.id,1)}>↓</button></div></article>)}</div><div className="dashboard-layout-actions"><button type="button" className="secondary-button" disabled={!layoutLoaded || savingLayout} onClick={() => { setWidgets(DEFAULT_WIDGETS); onDashboardPreferencesChange({ density: "comfortable", contentWidth: "standard" }); setNotice("Dashboard defaults restored. Save to apply them to your account."); setError("") }}>Reset all defaults</button><button type="button" className="primary-button" disabled={savingLayout || !layoutLoaded} onClick={() => void saveLayout()}>{savingLayout ? "Saving preferences…" : "Save all layout settings"}</button><button type="button" className="text-button" disabled={savingLayout || !layoutLoaded} onClick={() => onNavigate("executive")}>Preview overview →</button></div><p className="field-hint">Dashboard-wide appearance applies on this browser across the app. Executive Overview widget visibility and ordering are saved to your dashboard account. Hidden widgets remain available here.</p></section>
    </>}
  </div>
}

function viewTitle(view: View) { return ({ executive: "Executive Overview", health: "API Health & Data Freshness", trends: "Historical Trends and Comparisons", "member-insights": "Member Activity", "roster-insights": "Roster Insights", layout: "Customizable Dashboard Layout" })[view] }
function viewDescription(view: View) { return ({ executive: "A decision-ready summary of company performance, operational health, staffing, alerts, and competitive context.", health: "Separate Worker and database checks from the freshness of each saved company snapshot.", trends: "Compare income, star rating, and staffing across recorded snapshots, with period-over-period context.", "member-insights": "Dashboard account activity, account recency, and saved company-data coverage.", "roster-insights": "Review the selected company’s roster, role mix, capability averages, wages, tenure, and employee history depth.", layout: "Choose the dashboard widgets that matter to you and arrange your overview around your workflow." })[view] }
